### ISSUE TITLE
Error: [vite-ssg] Error on page:  ReferenceError: window is not defined

### ISSUE THREAD

**Issue by luizgringo** [antfu-collective/vite-ssg#417]
### Describe the bug

I tried to use `pnpm build` using `vite-ssg build` and received this error: 

```
[vite-ssg] Build for server...
vite v5.4.1 building SSR bundle for production...
✓ 54 modules transformed.
.vite-ssg-temp/3gs38p19w8/assets/style-ChH4TTz9.css   6.44 kB
.vite-ssg-temp/3gs38p19w8/main.mjs                   81.44 kB
✓ built in 685ms

[vite-ssg] Rendering Pages... (1)
file:///Users/etus_0128/Desktop/Projetos/quizmaker/frontend/node_modules/.pnpm/vite-ssg@0.23.8_vite@5.4.1_@types+node@20.16.1_sass-embedded@1.77.8_terser@5.31.6__vue@3.4.38_typescript@5.4.5_/node_modules/vite-ssg/dist/node.mjs:1058
        throw new Error(`${gray("[vite-ssg]")} ${red(`Error on page: ${cyan(route)}`)}
              ^

Error: [vite-ssg] Error on page: /
ReferenceError: window is not defined
    at file:///Users/etus_0128/Desktop/Projetos/quizmaker/frontend/.vite-ssg-temp/3gs38p19w8/main.mjs:2056:7
    at ReactiveEffect.fn (/Users/etus_0128/Desktop/Projetos/quizmaker/frontend/node_modules/.pnpm/@vue+reactivity@3.4.38/node_modules/@vue/reactivity/dist/reactivity.cjs.prod.js:928:13)
```

I know that has https://github.com/antfu-collective/vite-ssg/issues/23 similar error and i tried all that sugestions but i couldnt solve this problem. 

Somebody can help me with this issue?

### Reproduction

Running vite-ssg build

### System Info

```Shell
System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 60.07 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.5.2 - /usr/local/bin/npm
    pnpm: 9.1.3 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 127.1.68.134
    Chrome: 128.0.6613.86
    Safari: 17.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by zhangmo8** [comment]
This problem can be avoided by judging whether ssr is used. or use <ClinetOnly>

```html
  <ClientOnly> xxx </ClientOnly>
```

```ts

  if (!import.meta.env.SSR) {
  }

```

**Comment by BAHAA-THE-KING** [comment]
Also having this problem
